# brew tap-new uses this file to generate a PR test workflow for the new tap
name: brew test-bot

on:
  push:
    branches:
      - main
    paths: &paths-spec
      - "!Formula/*-intel.rb"
      - "!.github/workflows/tests-intel.yml"
  pull_request:
    paths: *paths-spec

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test-bot:
    strategy:
      matrix:
        # NOTE: also run on an Intel macOS runner, the Arch I'm on
        os: [ macos-26, macos-26-intel ]
        include:
          - os: ubuntu-latest
            container:
              image: ghcr.io/homebrew/brew:main
              options: --privileged
    runs-on: ${{ matrix.os }}
    container: ${{ fromJSON(toJSON(matrix.container)) }} # zizmor: ignore[unpinned-images]
    permissions:
      actions: read
      checks: read
      contents: read
      packages: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      # see comments in tests-intel.yml for why we need this
      - name: Pre-download gmp source
        if: runner.os == 'macOS' && runner.arch == 'X64'
        run: |
          set -euxo pipefail
          
          # url taken from https://github.com/Homebrew/homebrew-core/blob/75412ee44c0846f28739663c1c0d822ec949fb93/Formula/g/gnuplot.rb#L4
          url_hash=$(echo -n "https://ftpmirror.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz" | sha256sum | cut -d' ' -f1)
          # see release https://github.com/muzimuzhi/homebrew-beta/releases/tag/gmp-6.3.0
          gh release download -R ${{ github.repository }} gmp-6.3.0
          mkdir -p "$(brew --cache)/downloads"
          mv gmp-6.3.0.tar.xz "$(brew --cache)/downloads/${url_hash}--gmp-6.3.0.tar.xz"

          brew --cache --build-from-source gmp

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
      - name: Base64-encode GITHUB_TOKEN for HOMEBREW_DOCKER_REGISTRY_TOKEN
        id: base64-encode
        if: github.event_name == 'pull_request'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          base64_token=$(echo -n "${TOKEN}" | base64 | tr -d "\n")
          echo "::add-mask::${base64_token}"
          echo "token=${base64_token}" >> "${GITHUB_OUTPUT}"
      - run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/muzimuzhi/beta-test
        if: github.event_name == 'pull_request'
        env:
          HOMEBREW_DOCKER_REGISTRY_TOKEN: ${{ steps.base64-encode.outputs.token }}

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
